train:
  data_path: "/home/4/ud02274/navigation/my-VLN-CE/data/trajectories_dirs/cma/train_size512_trajectories_10496.lmdb"
  data_num: 10000 # Maybe it should be under 10,000, or error occurs.
  num_epochs: 2
  accum_iter: 8
  max_instruction_length: 40
  batch_size: 1
  learning_rate: 0.00001
  warmup_steps: 50
  logging_steps: 1
  lora:
    r: 16
    lora_alpha: 16
    lora_dropout: 0.1
    init_lora_weights: "gaussian"

val:
  data_path: "/home/4/ud02274/navigation/my-VLN-CE/data/trajectories_dirs/cma/val_unseen_size512_trajectories.lmdb"
  data_num: 10
  max_instruction_length: 40
