ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  
  FORWARD_STEP_SIZE: 0.25
  STEP_TIME: 0.25
  TURN_ANGLE: 10

  TYPE: "SoundSpacesSim"
  ACTION_SPACE_CONFIG: "v0"
  SCENE_DATASET: "replica"

  # 8-channel
  EIGHT_CHANNEL: False

  # Direct Map
  DIRECT_MAP_SIZE: null
  # DIRECT_MAP_SIZE: 8
  DIRECT_MAP_DISTANCE: "euclid"
  USE_GT_DIRECT_MAP: True
  DROPOUT_RATE: 0.2
  NOISE_COEF: 0.0
  DM_USE_VISUAL: False
  DISTANCE_TRANS_METHOD: "1d"
  CLIPPING: True
  DM_USE_GRU: False
  DM_CGO: False
  USE_CONV1D: True

  AUDIO:
    NUM: 1

TASK:
  TYPE: AudioNav
  SUCCESS_DISTANCE: 1.0

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'NORMALIZED_DISTANCE_TO_GOAL', 'SUCCESS', 'NUM_SOFT_SUCCESS', 'SPL', 'NUM_SOFT_SPL', 'SOFT_SPL', 'NUM_ACTION']
  # MEASUREMENTS: ['DISTANCE_TO_GOAL', 'NORMALIZED_DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL', 'NUM_ACTION', 'SUCCESS_WEIGHTED_BY_NUM_ACTION']
  SUCCESS:
    SUCCESS_DISTANCE: 1.0
  TOP_DOWN_MAP:
    MAP_RESOLUTION: 500
    DRAW_SOURCE_AND_TARGET: True
    DRAW_BORDER: True
    DRAW_SHORTEST_PATH: True
  
  NUM_SOFT_SUCCESS:
    SUCCESS_DISTANCE: 1.0

DATASET:
  TYPE: "AudioNav"
  SPLIT: "test_telephone_0"
  SOUND_TYPE: "multi_train"
  CONTENT_SCENES: ["*"]
  VERSION: "split_test"
  SAME_SOUND: False
  SCENE_DATASET: "replica"
  SCENES_DIR: "data/scene_datasets/replica"
  DATA_PATH: "data/datasets/audionav/replica/{version}/{split}/{split}.json.gz"
