model:
  vocab_embedding_size: 50
  num_encoder_layers: 3
  num_decoder_layers: 3
  emb_size: 512
  nhead: 8
  dim_feedforward: 512
  dropout_ratio: 0.3
  use_semantic: True
  lfao:
    use_lfao: False
    lfao_num_decoder_layers: 1

train:
  train_data_path: "/home/4/ud02274/navigation/my-VLN-CE/data/trajectories_dirs/xgen_pretraining/train_size336_trajectories.lmdb"
  train_data_num: 10819
  val_seen_data_path: "/home/4/ud02274/navigation/my-VLN-CE/data/trajectories_dirs/xgen_pretraining/val_seen_size336_trajectories.lmdb"
  val_seen_data_num: 778
  val_unseen_data_path: "/home/4/ud02274/navigation/my-VLN-CE/data/trajectories_dirs/xgen_pretraining/val_unseen_size336_trajectories.lmdb"
  val_unseen_data_num: 1839
  batch_size: 32
  use_image_feature: False
  dataset_drop_last: True
  learning_rate: 0.0001
  weight_decay: 0.0005
  skip_frame_per: 4
  feedback: "teacher" # teacher, student
  max_instruction_length: 80
  n_iters: 20000
  save_every: 10
  log_every: 1
  eval_every: 10
  lazy_loading: True
  use_cache: True
