BASE_TASK_CONFIG_PATH: "configs/audionav/av_nav/replica/multi_audiogoal.yaml"
NUM_PROCESSES: 1
SENSORS: ["DEPTH_SENSOR"]
# SENSORS: ["RGB_SENSOR","DEPTH_SENSOR"] # video
TEST_EPISODE_COUNT: 1000
GIF_VISUALIZATION: False
VIDEO_OPTION: []
# VIDEO_OPTION: ["disk"] # video
VISUALIZATION_OPTION: []

EVAL:
  SPLIT: "test_telephone_bell"
  USE_CKPT_CONFIG: True

RL:
  PPO:
    direct_map_loss_coef: 0
