ENVIRONMENT:
  MAX_EPISODE_STEPS: 2500
SIMULATOR:
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  
  FORWARD_STEP_SIZE: 0.25
  STEP_TIME: 0.25
  TURN_ANGLE: 10

  # Direct Map
  # DIRECT_MAP_SIZE: null
  DIRECT_MAP_SIZE: 8
  DIRECT_MAP_DISTANCE: "geodesic"
  USE_GT_DIRECT_MAP: True
  DROPOUT_RATE: 0.2
  NOISE_COEF: 0.0
  DM_USE_VISUAL: False
  DISTANCE_TRANS_METHOD: "1d"
  CLIPPING: True
  DM_USE_GRU: False
  DM_CGO: False
  USE_CONV1D: True

  TYPE: "SoundSpacesSim"
  ACTION_SPACE_CONFIG: "v0"
  SCENE_DATASET: "replica"
  GRID_SIZE: 1.0
  AUDIO:
    # RIR_SAMPLING_RATE: 16000
    RIR_SAMPLING_RATE: 44100
    NUM: 2

TASK:
  TYPE: AudioNav
  SUCCESS_DISTANCE: 1.0

  # SENSORS: ['AUDIOGOAL_SENSOR', 'SPECTROGRAM_SENSOR', 'POINTGOAL_WITH_GPS_COMPASS_SENSOR', 'POSE_SENSOR', 'LOCATION_BELIEF']
  SENSORS: ['DIRECT_MAP', 'AUDIOGOAL_SENSOR', 'SPECTROGRAM_SENSOR', 'POINTGOAL_WITH_GPS_COMPASS_SENSOR', 'POSE_SENSOR', 'LOCATION_BELIEF']
  GOAL_SENSOR_UUID: spectrogram
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "CARTESIAN"
    DIMENSIONALITY: 2

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'NORMALIZED_DISTANCE_TO_GOAL', 'SUCCESS', 'NUM_SOFT_SUCCESS', 'SPL', 'NUM_SOFT_SPL', 'SOFT_SPL', 'NUM_ACTION', 'FOUND_NUM']
  SUCCESS:
    SUCCESS_DISTANCE: 1.0
  NUM_SOFT_SUCCESS:
    SUCCESS_DISTANCE: 1.0
  
  TOP_DOWN_MAP:
    MAP_RESOLUTION: 500
    DRAW_BORDER: True
    DRAW_SHORTEST_PATH: True

DATASET:
  TYPE: "AudioNav"
  SPLIT: "train_telephone_bell"
  SOUND_TYPE: "multi_train"
  CONTENT_SCENES: ["*"]
  VERSION: 'v2'
  # VERSION: 'split_test'
  SCENES_DIR: "data/scene_datasets/replica"
  DATA_PATH: "data/datasets/audionav/replica/{version}/{split}/{split}.json.gz"
