BASE_TASK_CONFIG_PATH: "configs/semantic_audionav/savi/mp3d/semantic_audiogoal.yaml"
TRAINER_NAME: "ddppo"
NUM_PROCESSES: 8 # IPRLは6なら動く(はず)
SENSORS: ["DEPTH_SENSOR", "RGB_SENSOR"]
NUM_UPDATES: 20000
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 50
VIDEO_OPTION: []
VISUALIZATION_OPTION: []

EVAL:
  SPLIT: "val"
  USE_CKPT_CONFIG: True

RL:
  PPO:
    clip_param: 0.2
    ppo_epoch: 2
    num_mini_batch: 2
    iprl_loss_coef: 0.2
    value_loss_coef: 0.5
    direct_map_loss_coef: 100
    entropy_coef: 0.05
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.2
    # decide the length of history that ppo encodes
    num_steps: 150
    hidden_size: 512
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: False
    use_linear_lr_decay: False
    # window size for calculating the past rewards
    reward_window_size: 50
    use_normalized_advantage: False
    policy_type: "smt"
    use_belief_predictor: True # belief_predictorを使うかどうか。FalseならbeliefはNoneになる
    use_external_memory: True  # external_memoryを使うかどうか
    SCENE_MEMORY_TRANSFORMER:
      memory_size: 1 # ExternalMemoryのcapacity
      hidden_size: 256 # Transformerのhiddenサイズ
      nhead: 8 # Transformerのヘッド数
      num_encoder_layers: 1 # Transformerのencoder数
      num_decoder_layers: 1 # Transformerのdecoder数
      dropout: 0.0
      activation: 'relu'
      use_pretrained: False # SMTのpretrainedのモデルを使うかどうか
      pretrained_path: '' # pretrainedのモデルを使う場合のpretrainedのモデルのパス
      use_xgen_visual_encoder: True # XGeneratorで使われているVisualEncoderにするか、デフォルトのSMTCNNにするか
      freeze_encoders: False # encoder(visual, action, goal)をfreezeさせるかどうか
      pretraining: True # savi1stであるかどうか（正確にはexternal_memoryからの入力をmaskするかどうか）
    BELIEF_PREDICTOR: 
      online_training: True # BeliefPredictorのpredictorを学習するかどうか
      train_encoder: False # visual_enc, action_enc, goal_encをBeliefPredictorのoptimizerに入れるかどうか
      lr: 1e-3 
      use_label_belief: True # Categoryのbeliefを使うかどうか
      use_location_belief: True # Locationのbeliefを使うかどうか
    INSTRUCTION_PREDICTOR:
      use_iprl: False # IPRLを行うかどうか
      max_instr_len: 40
      num_decoder_layers: 1
      vocab_emb_size: 50
      emb_size: 256 # IPのembサイズ。SMTのemb_sizeと同じである必要がある
      nhead: 8
      dim_feedforward: 512
      dropout: 0.2
      iprl_use_gt_D: True
      feedback: "teacher" # teacher or student
      use_bos: False
      use_instruction_predictor: False
      use_next_action_predictor: False
      use_progress_predictor: False
      use_next_frame_predictor: False
      use_next_spectrogram_predictor: False
      use_audio_position_predictor: False
      use_audio_category_predictor: False
  DDPPO:
    sync_frac: 0.6
    distrib_backend: "NCCL"
    rnn_type: "GRU"
    num_recurrent_layers: 1
    backbone: "custom_resnet18"
    pretrained_weights: "" # SMT以外の事前学習済みモデルを使う場合の事前学習済みモデルのパス
    pretrained: False # 事前学習済みモデルを使うかどうか。ただしSMT以外(encoder, actor, critic)
    reset_critic: False # criticをリセットするかどうか
